Add multi-schema support to the json_stream_sampler
ovis-hpc/ldms pull request #1516
Opened 2024-11-14 17:40 UTC by tom95858

This change adds support for multiple schema to the json_stream_sampler.

2024-11-15 18:07 UTC, baallan requested changes
@tom95858 this is in the right direction, but it turns out the spank and netlink use cases need a schema_format (akin instance_format) option to work well. Details in the review.

2024-11-15 18:10 UTC, baallan commented
Man page needs updating once the changes are settled.

2024-11-15 23:17 UTC, tom95858 commented on ldms/src/sampler/json/json_stream_sampler.c
> +	"config name=js_stream_sampler producer=<prod_name> \n"
@baallan, I think you are correct.

2024-11-19 19:06 UTC, merged

2024-12-10 19:59 UTC, emdonat commented
@tom95858 You mentioned last week that a fix for this could be done easily.  Can you update status?