Rename and update Sampler Advertisement man page
ovis-hpc/ldms pull request #1531
Opened 2024-11-21 15:35 UTC by nichamon

2024-11-21 22:07 UTC, tom95858 commented
@nichamon, these really aren't sampler advertisements...correct? They are ldmsd peer advertisements. The ldmsd peer may have no samplers at all.

2024-11-21 22:08 UTC, tom95858 commented on ldms/man/ldmsd_sampler_advertisement.man
> +LDMSD Sampler Advertisement is a capability that enables LDMSD automatically add
LDMSD Peer Daemon advertisement is a capability that enables LDMSD to automatically add

2024-11-21 22:10 UTC, tom95858 requested changes
@nichamon ... should we change the man file name?

2024-11-21 22:10 UTC, tom95858 commented on ldms/man/ldmsd_sampler_advertisement.man
>  producers that its hostname matches a given regular expression. The feature
producers for advertisers whose hostname matches a regular expression.

2024-11-21 22:10 UTC, tom95858 commented on ldms/man/ldmsd_sampler_advertisement.man
>  eliminates the need for manual configuration of sampler hostname in the
reduces the need for the manual configuration of producers in configuration files

2024-11-21 22:52 UTC, nichamon commented
> @nichamon ... should we change the man file name?

Yes, I agree.

2024-12-09 19:28 UTC, tom95858 commented
@nichamon is this ready to go?

2024-12-09 19:29 UTC, merged