Add requests to enable/disable streams communication
ovis-hpc/ldms pull request #1543
Opened 2024-12-02 23:52 UTC by tom95858

This change adds commands to enable and disable stream support in the ldmsd daemon. When streams communication is disabled, stream cannot be published to or subscribed from the daemon.

The current default of enabled is maintained.

2024-12-03 15:56 UTC, tom95858 commented
@morrone, @emdonat I'm going to modify this pull request so that the default enabled vs. disabled is controlled by a configure option. Does that work for everyone?

2024-12-03 15:59 UTC, nick-enoent commented
> @morrone, @emdonat I'm going to modify this pull request so that the default enabled vs. disabled is controlled by a configure option. Does that work for everyone?

I was about to ask about this. We'll need to add a YAML option to address this as well.

2024-12-03 20:03 UTC, nichamon commented
@tom95858 In `prdcr_subscribe` path, maybe aggregators could report the error message responded by the producer when it has  Streams disabled. I'm talking about having [ldmsd_prdcr.c:__on_subs_resp()](https://github.com/ovis-hpc/ldms/blob/ffd70a8ec11a7c6e7a913b7a87bfd566542268d0/ldms/src/ldmsd/ldmsd_prdcr.c#L498) print the error message it receives in the response.

To support `stream_enable` and `stream_disable` commands in configuration files, could you please add the strings to this table: [ldmsd_request_util.c:req_str_id_table](https://github.com/ovis-hpc/ldms/blob/ffd70a8ec11a7c6e7a913b7a87bfd566542268d0/ldms/src/ldmsd/ldmsd_request_util.c#L64C25-L64C41)?

Could you also add the commands to the[ ldmsd_controller man page](https://github.com/ovis-hpc/ldms/blob/b4.4/ldms/man/ldmsd_controller.man)?

2024-12-03 20:04 UTC, nichamon requested changes
@tom95858 In `prdcr_subscribe` path, maybe aggregators could report the error message responded by the producer when it has  Streams disabled. I'm talking about having [ldmsd_prdcr.c:__on_subs_resp()](https://github.com/ovis-hpc/ldms/blob/ffd70a8ec11a7c6e7a913b7a87bfd566542268d0/ldms/src/ldmsd/ldmsd_prdcr.c#L498) print the error message it receives in the response.

To support `stream_enable` and `stream_disable` commands in configuration files, could you please add the strings to this table: [ldmsd_request_util.c:req_str_id_table](https://github.com/ovis-hpc/ldms/blob/ffd70a8ec11a7c6e7a913b7a87bfd566542268d0/ldms/src/ldmsd/ldmsd_request_util.c#L64C25-L64C41)?

Could you also add the commands to the[ ldmsd_controller man page](https://github.com/ovis-hpc/ldms/blob/b4.4/ldms/man/ldmsd_controller.man)?

2024-12-03 20:29 UTC, morrone commented
I would like to see most of the streams rpcs rejected even earlier in ldmsd_handle_request() when streams is disabled. Something like:

```
  if streams_disabled() && is_streams_rpc():
     return unimplemented_handler();
```

Or instead of unimplemented_handler(), it could be a new streams_disabled_handler().

2024-12-04 02:31 UTC, tom95858 commented
@morrone, this has already been accomplished in top of tree. What you propose would require dipping down into the LDMS layer which is explicitly **_not_** what this streams implementation wanted to do. The top of tree implementation is in the LDMS layer like you suggest. The 4.4 implementation sits on top of LDMS and looks like an **application** to the system. This is why we re-implemented it. My only point is that if we **_really_** want all of this in 4.4 then we should back-port the top of tree streams implementation, not fuss about with an implementation that is going to be deprecated in 6 mos.

2024-12-04 03:16 UTC, nichamon commented
@tom95858 I believe @morrone referred to [`ldmsd_handle_request()`](https://github.com/ovis-hpc/ldms/blob/fd189261297901305f90aeeb6ee489d167d3fc6d/ldms/src/ldmsd/ldmsd_request.c#L953) in `ldmsd_request.c` in the `ldmsd` layer. The check he mentioned could be added right after the request ID validation [here](https://github.com/ovis-hpc/ldms/blob/fd189261297901305f90aeeb6ee489d167d3fc6d/ldms/src/ldmsd/ldmsd_request.c#L971).

2024-12-04 03:22 UTC, nichamon commented
@tom95858 I also believe we should add `stream_disable` to the priority list in [`is_req_id_priority()`](https://github.com/ovis-hpc/ldms/blob/fd189261297901305f90aeeb6ee489d167d3fc6d/ldms/src/ldmsd/ldmsd_request.c#L679) so that streams would be disabled before `ldmsd` listens on a listening port. This will ensure that `ldmsd` wouldn't handle any stream publish request after listening but before disabling Streams. What do you think? Let me know if you want me to make a patch and send it to you.

2024-12-06 19:20 UTC, morrone commented
> @tom95858 I believe @morrone referred to [`ldmsd_handle_request()`](https://github.com/ovis-hpc/ldms/blob/fd189261297901305f90aeeb6ee489d167d3fc6d/ldms/src/ldmsd/ldmsd_request.c#L953) in `ldmsd_request.c` in the `ldmsd` layer. The check he mentioned could be added right after the request ID validation [here](https://github.com/ovis-hpc/ldms/blob/fd189261297901305f90aeeb6ee489d167d3fc6d/ldms/src/ldmsd/ldmsd_request.c#L971).

Yes, that is what I was talking about.

> @tom95858 I also believe we should add `stream_disable` to the priority list in [`is_req_id_priority()`](https://github.com/ovis-hpc/ldms/blob/fd189261297901305f90aeeb6ee489d167d3fc6d/ldms/src/ldmsd/ldmsd_request.c#L679) so that streams would be disabled before `ldmsd` listens on a listening port. This will ensure that `ldmsd` wouldn't handle any stream publish request after listening but before disabling Streams. What do you think? Let me know if you want me to make a patch and send it to you.

That sounds good to me!

2024-12-06 19:26 UTC, morrone commented
By the way, @tom95858 , it doesn't look like the PR had checks for LDMSD_STREAM_CLIENT_DUMP_REQ or LDMSD_STREAM_NEW_REQ. Shouldn't those be blocked as well?

2024-12-06 19:51 UTC, tom95858 commented
@morrone sure we can add those checks.

2024-12-07 00:54 UTC, morrone commented
> @morrone, this has already been accomplished in top of tree

I don't believe that it has.

2024-12-07 01:10 UTC, tom95858 commented
@morrone, that may be you to explain why. Otherwise, we can't possibly resolve the issue.

2024-12-07 22:22 UTC, morrone commented
> @morrone, that may be you to explain why. Otherwise, we can't possibly resolve the issue.

See discussion #1548. When those questions have technical solutions, we'll have resolved the issues.

2024-12-09 20:23 UTC, tom95858 commented
> @tom95858 In `prdcr_subscribe` path, maybe aggregators could report the error message responded by the producer when it has Streams disabled. I'm talking about having [ldmsd_prdcr.c:__on_subs_resp()](https://github.com/ovis-hpc/ldms/blob/ffd70a8ec11a7c6e7a913b7a87bfd566542268d0/ldms/src/ldmsd/ldmsd_prdcr.c#L498) print the error message it receives in the response.
> 
> To support `stream_enable` and `stream_disable` commands in configuration files, could you please add the strings to this table: [ldmsd_request_util.c:req_str_id_table](https://github.com/ovis-hpc/ldms/blob/ffd70a8ec11a7c6e7a913b7a87bfd566542268d0/ldms/src/ldmsd/ldmsd_request_util.c#L64C25-L64C41)?
> 
> Could you also add the commands to the[ ldmsd_controller man page](https://github.com/ovis-hpc/ldms/blob/b4.4/ldms/man/ldmsd_controller.man)?

I think this brings up another issue. What if streams are disabled and then subsequently enabled? Isn't it free to subscribe? In other words allowing the subscription to succeed but never delivering anything is "free". @morrone, what do you think?

2024-12-09 22:54 UTC, tom95858 commented
@morrone, @nichamon could you please review this latest update and ensure that your concerns have. been addressed?

2024-12-09 23:46 UTC, morrone commented
> I think this brings up another issue. What if streams are disabled and then subsequently enabled? Isn't it free to subscribe? In other words allowing the subscription to succeed but never delivering anything is "free". @morrone, what do you think?

I don't think that we want clients maintaining stale subscriptions in the ldmsd when streams are disabled. In fact, when streams are disabled, the code should probably explicitly close and free resources associated with any outstanding subscribers.

2024-12-09 23:52 UTC, oceandlr commented
Is this about enabling/disabling it forever? Or about enabling or disabling particular streams dynamically?

2024-12-10 00:01 UTC, morrone commented
> Is this about enabling/disabling it forever? Or about enabling or disabling particular streams dynamically?

This ticket is about having one big switch that enables or disables the entire streams service in an ldmsd. When disabled, none of the streams related rpcs (other than enable/disable) will be usable on the ldmsd.

So "forever" isn't really a word that applies here. One _could_ choose to "enable" the streams service at any time (though expect that those of us that will disable the service will leave it off for the lifetime of the ldmsd process).

2024-12-10 00:11 UTC, oceandlr commented
Ah, ok. I am working on a test case of setting up and tearing down streams dynamically, rather than in the configuration, as they were done in 4.4.4.

2024-12-10 01:14 UTC, tom95858 commented
> > I think this brings up another issue. What if streams are disabled and then subsequently enabled? Isn't it free to subscribe? In other words allowing the subscription to succeed but never delivering anything is "free". @morrone, what do you think?
> 
> I don't think that we want clients maintaining stale subscriptions in the ldmsd when streams are disabled. In fact, when streams are disabled, the code should probably explicitly close and free resources associated with any outstanding subscribers.

Ok, but the subscribers don't know that the publisher has disabled streams. This flows all the way up the forwarding chain. All that would be saved from this additional functionality is a few bytes of memory at the cost of a significant amount of complexity.

2024-12-10 03:47 UTC, nichamon commented
> @tom95858 In prdcr_subscribe path, maybe aggregators could report the error message responded by the producer when it has Streams disabled. I'm talking about having [ldmsd_prdcr.c:__on_subs_resp()](https://github.com/ovis-hpc/ldms/blob/ffd70a8ec11a7c6e7a913b7a87bfd566542268d0/ldms/src/ldmsd/ldmsd_prdcr.c#L498) print the error message it receives in the response.

I suggested this so that there would be a log message in the aggregator log file that `prdcr_subscribe` didn't success or complete. With out `__on_subs_resp()` reports the error message, there is no way we will know that streams are disabled on some sampler daemons.

2024-12-10 04:11 UTC, nichamon commented
> I think this brings up another issue. What if streams are disabled and then subsequently enabled? Isn't it free to subscribe? In other words allowing the subscription to succeed but never delivering anything is "free".

This is an interesting point. Initially, we added the stream_enable and stream_disable commands to address a specific use case where administrators want to permanently disable streaming features. Your question brings up additional scenarios to consider - specifically what happens when streams are temporarily disabled and then re-enabled.

In the case of temporary pausing, there's value in preserving the subscriber list while streams are disabled. This would eliminate the need for reconfiguration when streams are re-enabled. While I understand @morrone's suggestion to purge subscribers, I believe administrators should have the flexibility to maintain their subscriber configurations across disable/enable cycles.

I propose we keep the current implementation of this pull request (where ldmsd doesn't receive stream data or new subscribers while disabled) but add a new stream_unsubscribe command to ldmsd_controller. This would give administrators manual control over removing stale subscribers when needed.

2024-12-10 04:13 UTC, nichamon requested changes

2024-12-10 04:13 UTC, nichamon commented on ldms/man/ldmsd_controller.man
> +.BR stream_enable
A typo. This should read `stream_disable`.

2024-12-10 04:13 UTC, nichamon commented on ldms/src/ldmsd/ldmsd_request.c
> +		&& id <= LDMSD_STREAM_STATUS_REQ);
Should we add `PRDCR_SUBSCRIBE` here?

2024-12-10 16:43 UTC, nichamon commented
@tom95858 @morrone After further consideration of the motivation behind adding these commands, I believe we shouldn't allow administrators to enable Streams after they disable it. Allowing temporary disabling of Streams would introduce additional complexities that would need to be carefully handled. Since the disable action should be permanent, we should consider removing the `stream_enable` command entirely and document that `stream_disable` is permanent, requiring an ldmsd restart to re-enable Streams. What do you think?

2024-12-10 17:30 UTC, morrone commented
> @tom95858 @morrone After further consideration of the motivation behind adding these commands, I believe we shouldn't allow administrators to enable Streams after they disable it. Allowing temporary disabling of Streams would introduce additional complexities that would need to be carefully handled. Since the disable action should be permanent, we should consider removing the `stream_enable` command entirely and document that `stream_disable` is permanent, requiring an ldmsd restart to re-enable Streams. What do you think?

That is fine with me. I don't really have a use case for reenabling (we can always just restart the ldmsd with a different configuration to have streams enabled).

If we don't yet have your earlier suggestion of "I also believe we should add stream_disable to the priority list in [is_req_id_priority()](https://github.com/ovis-hpc/ldms/blob/fd189261297901305f90aeeb6ee489d167d3fc6d/ldms/src/ldmsd/ldmsd_request.c#L679) so that streams would be disabled before ldmsd listens on a listening port. This will ensure that ldmsd wouldn't handle any stream publish request after listening but before disabling Streams.", I think we should have that as well.

Either that or clean up any subscriptions at stream_disable() time, but @tom95858, you seem opposed to that on complexity grounds.

2024-12-10 23:58 UTC, nichamon commented
@tom95858 already added the commands to the priority list, so I think the patch is good to be merged after @tom95858 removes the `stream_enable` logic.

2024-12-11 04:23 UTC, merged